spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/ponte_images?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: test1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true

s3:
  accessKey: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  region: YOUR_REGION
  bucket: YOUR_BUCKET
